import {
  STAFF_SLIPS_TYPE,
} from '../../../src/constants';

export const STAFF_SLIP_WITH_OUT_DATA = {
  'item.allContributors': undefined,
  'item.barcode': undefined,
  'item.barcodeImage': '<Barcode>undefined</Barcode>',
  'item.callNumber': undefined,
  'item.callNumberPrefix': undefined,
  'item.callNumberSuffix': undefined,
  'item.chronology': undefined,
  'item.copy': undefined,
  'item.descriptionOfPieces': undefined,
  'item.displaySummary': undefined,
  'item.effectiveLocationCampus': undefined,
  'item.effectiveLocationInstitution': undefined,
  'item.effectiveLocationLibrary': undefined,
  'item.effectiveLocationPrimaryServicePointName': undefined,
  'item.effectiveLocationSpecific': undefined,
  'item.enumeration': undefined,
  'item.fromServicePoint': undefined,
  'item.lastCheckedInDateTime': undefined,
  'item.loanType': undefined,
  'item.materialType': undefined,
  'item.numberOfPieces': undefined,
  'item.primaryContributor': undefined,
  'item.title': undefined,
  'item.toServicePoint': undefined,
  'item.volume': undefined,
  'item.yearCaption': undefined,
  'request.deliveryAddressType': undefined,
  'request.holdShelfExpirationDate': undefined,
  'request.patronComments': undefined,
  'request.requestDate': undefined,
  'request.requestExpirationDate': undefined,
  'request.requestID': undefined,
  'request.servicePointPickup': undefined,
  'requester.addressLine1': undefined,
  'requester.addressLine2': undefined,
  'requester.barcode': undefined,
  'requester.barcodeImage': '',
  'requester.city': undefined,
  'requester.country': '',
  'requester.departments': undefined,
  'requester.firstName': undefined,
  'requester.lastName': undefined,
  'requester.middleName': undefined,
  'requester.patronGroup': undefined,
  'requester.preferredFirstName': undefined,
  'requester.stateProvRegion': undefined,
  'requester.zipPostalCode': undefined,
  'staffSlip.Name': STAFF_SLIPS_TYPE.TRANSIT_MEDIATED_REQUESTS,
  'staffSlip.currentDateTime': 'Invalid date',
};

export const SOURCE_FOR_STAFF_SLIP_DATA = {
  currentDateTime: '2024-12-31T24:00:00.000+00:00',
  requester: {
    firstName: 'requester.firstName',
    lastName: 'requester.lastName',
    middleName: 'requester.middleName',
    preferredFirstName: 'requester.preferredFirstName',
    patronGroup: 'requester.patronGroup',
    addressLine1: 'requester.addressLine1',
    addressLine2: 'requester.addressLine2',
    countryId: 'requester.countryId',
    city: 'requester.city',
    region: 'requester.region',
    postalCode: 'requester.postalCode',
    barcode: 'requester.barcode',
    departments: 'requester.departments',
  },
  item: {
    title: 'item.title',
    primaryContributor: 'item.primaryContributor',
    allContributors: 'item.allContributors',
    barcode: 'item.barcode',
    callNumber: 'item.callNumber',
    callNumberPrefix: 'item.callNumberPrefix',
    callNumberSuffix: 'item.callNumberSuffix',
    displaySummary: 'item.displaySummary',
    enumeration: 'item.enumeration',
    volume: 'item.volume',
    chronology: 'item.chronology',
    copy: 'item.copy',
    yearCaption: 'item.yearCaption',
    materialType: 'item.materialType',
    loanType: 'item.loanType',
    numberOfPieces: 'item.numberOfPieces',
    descriptionOfPieces: 'item.descriptionOfPieces',
    lastCheckedInDateTime: '2024-12-31T24:00:00.000+00:00',
    fromServicePoint: 'item.fromServicePoint',
    toServicePoint: 'item.toServicePoint',
    effectiveLocationInstitution: 'item.effectiveLocationInstitution',
    effectiveLocationCampus: 'item.effectiveLocationCampus',
    effectiveLocationLibrary: 'item.effectiveLocationLibrary',
    effectiveLocationSpecific: 'item.effectiveLocationSpecific',
    effectiveLocationPrimaryServicePointName: 'item.effectiveLocationPrimaryServicePointName',
  },
  request: {
    servicePointPickup: 'request.servicePointPickup',
    deliveryAddressType: 'request.deliveryAddressType',
    requestExpirationDate: '2024-12-31T24:00:00.000+00:00',
    requestDate: '2024-12-31T24:00:00.000+00:00',
    holdShelfExpirationDate: '2024-12-31T24:00:00.000+00:00',
    requestID: 'request.requestID',
    patronComments: 'request.patronComments',
  },
};

export const STAFF_SLIP_DATA = {
  'item.allContributors': 'item.allContributors',
  'item.barcode': 'item.barcode',
  'item.barcodeImage': '<Barcode>item.barcode</Barcode>',
  'item.callNumber': 'item.callNumber',
  'item.callNumberPrefix': 'item.callNumberPrefix',
  'item.callNumberSuffix': 'item.callNumberSuffix',
  'item.chronology': 'item.chronology',
  'item.copy': 'item.copy',
  'item.descriptionOfPieces': 'item.descriptionOfPieces',
  'item.displaySummary': 'item.displaySummary',
  'item.effectiveLocationCampus': 'item.effectiveLocationCampus',
  'item.effectiveLocationInstitution': 'item.effectiveLocationInstitution',
  'item.effectiveLocationLibrary': 'item.effectiveLocationLibrary',
  'item.effectiveLocationPrimaryServicePointName': 'item.effectiveLocationPrimaryServicePointName',
  'item.effectiveLocationSpecific': 'item.effectiveLocationSpecific',
  'item.enumeration': 'item.enumeration',
  'item.fromServicePoint': 'item.fromServicePoint',
  'item.lastCheckedInDateTime': '2024-12-31T24:00:00.000+00:00',
  'item.loanType': 'item.loanType',
  'item.materialType': 'item.materialType',
  'item.numberOfPieces': 'item.numberOfPieces',
  'item.primaryContributor': 'item.primaryContributor',
  'item.title': 'item.title',
  'item.toServicePoint': 'item.toServicePoint',
  'item.volume': 'item.volume',
  'item.yearCaption': 'item.yearCaption',
  'request.deliveryAddressType': 'request.deliveryAddressType',
  'request.holdShelfExpirationDate': '2024-12-31T24:00:00.000+00:00',
  'request.patronComments': 'request.patronComments',
  'request.requestDate': '2024-12-31T24:00:00.000+00:00',
  'request.requestExpirationDate': '2024-12-31T24:00:00.000+00:00',
  'request.requestID': 'request.requestID',
  'request.servicePointPickup': 'request.servicePointPickup',
  'requester.addressLine1': 'requester.addressLine1',
  'requester.addressLine2': 'requester.addressLine2',
  'requester.barcode': 'requester.barcode',
  'requester.barcodeImage': '<Barcode>requester.barcode</Barcode>',
  'requester.city': 'requester.city',
  'requester.country': 'stripes-components.countries.requester.countryId',
  'requester.departments': 'requester.departments',
  'requester.firstName': 'requester.firstName',
  'requester.lastName': 'requester.lastName',
  'requester.middleName': 'requester.middleName',
  'requester.patronGroup': 'requester.patronGroup',
  'requester.preferredFirstName': 'requester.preferredFirstName',
  'requester.stateProvRegion': 'requester.region',
  'requester.zipPostalCode': 'requester.postalCode',
  'staffSlip.Name': STAFF_SLIPS_TYPE.TRANSIT_MEDIATED_REQUESTS,
  'staffSlip.currentDateTime': '01/01/2025 12:00 AM',
};
